#!/usr/bin/env bash
# Kazanim koruyucusu: deploy oncesi zorunlu. Eksik varsa deploy DURUR.
# Yeni bir ozellik eklendiginde buraya bir satir eklenir.
set -uo pipefail
cd "$(dirname "$0")/.."
FAIL=0
check() { grep -q "$2" "$1" 2>/dev/null || { echo "EKSIK: $1 -> $3"; FAIL=1; }; }
check web/demo.html           "object-fit:fill"        "video fill (oran duzeltmesi)"
check web/demo.html           "liveBadge"              "canli rozeti / kontrolsuz canli"
check web/demo.html           "buildTimeline"          "gun cizelgesi (DVR akis)"
check web/demo.html           "location.hostname"      "canli URL host duzeltmesi"
check web/demo.html           "playAt"                 "kesintisiz segment akisi"
check edgeway/config.py       "except OSError"         "env okunamazsa ayakta kal"
check edgeway/config.py       "FFMPEG_EXTRA"           "ffmpeg ek parametre (hvc1)"
check edgeway/config.py       "MAX_STORAGE_GB"         "boyut tavani"
check edgeway/config.py       "def live_paths"         "canli path eslemesi"
check edgeway/recorder/segmenter.py "_pipe_masked"     "ffmpeg log maskesi"
check edgeway/recorder/segmenter.py "KEEP_LAST"        "segment-bazli retention"
check edgeway/uploader/s3sync.py "return 0 if fail == 0 else 1" "uploader durust exit"
check deploy/install.sh       "chmod 640"              "env 640 root:edgeway"
check deploy/install.sh       "edgeway-apply-env"      "sihirbaz sudo helper"
check edgeway/provision/routes.py "setup_apply"        "kurulum sihirbazi"
check infra/bootstrap_aws.sh  "command -v aws"         "aws cli on-kontrol"
check edgeway/mediamtx_common/generator.py "sourceOnDemand" "mediamtx generator (surumden bagimsiz)"
check docs/SOURCES_SCHEMA.md  "cameras_selected"       "kaynaklar veri modeli"
check edgeway/mediamtx_common/apply.py "_sub"           "canli dual-path (main+sub)"
check deploy/systemd/edgeway-uploader.service "TimeoutStartSec" "uploader zaman asimi"
check edgeway/api/main.py     "api_storage"            "depolama gorunurlugu"
check web/demo.html           "relTime"                "goreli zaman etiketleri"
check web/demo.html           "atlandi"                "bozuk segment atlama"
check web/demo.html           "jogWrap"                "jog kadrani (ince ayar)"
check web/demo.html           "setNote"                "tek gecici hata notu"
check web/demo.html           "syncSeekTo"             "coklu kamera senkron playback"
check web/demo.html           "syncTick"               "senkron kapsama disi karartma"
check web/demo.html           "mergedSegs"             "birlesik takvim (lokal+bulut tek gorunum)"
check web/demo.html           "camDays"                "tekli oynatimda da birlesik gunler"
check web/demo.html           "attachZoom"             "tikla-buyut (3 kademe)"
check web/demo.html           "jogTime"                "jog realtime buyuk saat"
check web/demo.html           "calGrid"                "aylik takvim"
check web/demo.html           "selCams"                "senkron kamera secimi (limit 4)"
check web/demo.html           "camOff"                 "faz farki menusu"
check web/demo.html           "clampSeek"              "canli arkasi kor bolge kelepcesi"
check edgeway/recorder/segmenter.py "faststart"        "bulut oynatim aninda acilis"
check edgeway/events/routes.py "api/events"          "olay webhook girisi"
check edgeway/events/clipper.py "cut_clip"            "ring tampondan klip kesici"
check edgeway/uploader/s3sync.py "pending_clips"      "clips yukleme kanali"
check edgeway/uploader/s3sync.py "ckey if ckey else"  "klip anahtari dogru rafta"
check edgeway/config.py       "UPLOAD_MODE"            "plan bayragi (event/continuous)"
check docs/EVENTS_API.md      "clip_eta_s"             "CamMind sozlesme dokumani"
check web/demo.html           "goLive"                 "kesintisiz canli-gecmis (time-shift)"
check scripts/attach_ssd.sh   "EDGEWAY_MAX_STORAGE_GB" "tek komut SSD gecisi"
check edgeway/recorder/segmenter.py "_newest_age"      "stall nobetcisi (180sn)"
check edgeway/heartbeat/agent.py "rec_age_s"           "nabizda kayit yasi"
check edgeway/config.py       "CLIPS_MAX_GB"           "klip tavani ayari"
check edgeway/recorder/segmenter.py "enforce_clips_retention" "klip retention (yalnizca .up silinir)"
check edgeway/health/engine.py "def snapshot"     "yerel saglik motoru (tek hesap noktasi)"
check edgeway/health/engine.py "def last24h"      "24s saglik gecmisi ve bosluk ozeti"
check edgeway/health/engine.py "days\[:2\]"        "rec_age taramasi arsivle buyumez"
check edgeway/recorder/segmenter.py "health_loop" "saglik gecmisi yaziliyor"
check edgeway/health/engine.py "GRACE_S"           "acilis toleransi (deploy sonrasi sahte alarm yok)"
check edgeway/storage.py "RETENTION_SECONDS" "saklama sureleri tablosu"
check edgeway/storage.py "pinned_prefixes" "sabitlenmis kayitlar korunur"
check deploy/systemd/edgeway-sweeper.timer "OnUnitActiveSec" "supurucu zamanlayici"
check deploy/install.sh "edgeway-sweeper.timer" "supurucu kurulumda etkinlesir"
check edgeway/storage.py "buluta cikmadigi icin korundu" "yuklenmemis kayit asla silinmez"
check web/storage.html "api/storage/cost" "panel veriyi API den alir"
check edgeway/api/main.py "api/storage/cost" "depolama maliyet ucu"
check edgeway/api/main.py "api/storage/policy" "panelden saklama ve mod degistirme"
check edgeway/api/main.py "YALNIZCA verilen anahtarlari" "env yamasi digerlerini silmez"
check edgeway/storage.py "uploader_timer_state" "panel config i degil sistemi gosterir"
check edgeway/config.py "RECORD_CAMERAS" "kamera basina kayit secimi"
check edgeway/api/main.py "api/cameras/record" "canlidan kayit ac kapa ucu"
check web/demo.html "REC-BADGE-v1" "kayit rozeti kutucugun uzerinde ve tiklanabilir"
check web/demo.html "CAMGRID-v2" "kamera listesi altta, rozet ismin yaninda"
[ $FAIL -eq 0 ] && echo "TUM KAZANIMLAR YERINDE ($(grep -c '^check ' "$0") kontrol)" || exit 1
